### ISSUE TITLE
missing field in openflow.h/struct ofp_table_stats in pylibopenflow

### ISSUE THREAD

**Issue by andreaskoepsel** [CPqD/oftest12#1]
Hi all,

tools/pylibopenflow/include/openflow.h defines the C structures for OpenFlow version 1.2. 
The OpenFlow specification defines the struct ofp_table_stats to contain 128 bytes in total.
However, the version defined in the pylibopenflow directory lacks the uint64_t field metadata_match, resulting in an overall length of 120 bytes. Consequently, running the basic.TableGetStats test yields always an error like "ERROR unpacking table stats string: extra bytes".
Was that field intentionally removed? 

Thanks and regards,
Andreas Koepsel

**Comment by rrdenicol** [comment]
Thank you Andreas for bringing this issue to our attention. We don't really know how that field ended up being out of our release version, but we are working on solving this issue asap.

**Comment by rrdenicol** [comment]
Hi Andreas,
Just committed some changes that should solve this issue!
Thanks again for the input.
